language: python
python:
- 3.6.3
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: app-portfolio-nath
  on:
    branch: master
  api_key:
    secure: $HEROKU_API_KEY
