language: python
python:
- 3.6.3
script:
- python test.py
deploy:
  provider: heroku
  app: app-nath-python
  on:
    branch: master
  api_key:
    secure: agNp3uahVb0SZPlOxgRQuYDAkCZT5HkQVw8RGzUM6NO2+fWhnqJ8iKksiaFEMcRoRSSZKsDvJqeh74kM2bn1W+v5i8wcEaMLAPPAFdamv/9M1usnKQU+ZXYKVoQKxlxzpgtLaWUP3HTmdtT5EGZt6WD15uYkLXmnIiOCnsFRJDFlDiOvvi/SJmkTZyWh/g7IDgOYVMlrwUzIPu/malxRXTAFQDwCBKumC7arQzYyPOsSU2Md5JFrDMv4EuVDMJU5xA2cxdCnNbRjMGFqjpzheeaQ6A25eNNUxVSPFK6GA2X5po1CvzvCmrx+oEj+7T/OIZRbk9Mp5j3g69di3sir+X4uEJzrSxraNBMqMfGQsFcI+aDy87TBZRuWtMWhRWcka0NPgZfdeP+xpv2XZliEMR+wzcrC27vwnfQ1AAGcGtGMzj31y7d1iyccOSMbWPkewXANULCCwxVp5k4ZDQO2tsfyEFzyFkHgVZE5SWr7OiyPsz4tr+K7zv2o7tFWJzK3gRzy8/a82JkF8rk4SRRNm/sUaZ9LpzKxzt91peGYTs3S61VTn09OMhxHvW5RP3aii/gzpPlCrRcTcwD8NWg3ze20Ze9Y9xptcAyyNZJLoH/KwKVF2HrcjJtxsVC0axzVXIMycCBubfq5dTANvYaPz6Z2D9kXZwhRyikoQwQ1+nQ=
