language: python
python:
- 3.6.3
script:
- python test.py
deploy:
  provider: heroku
  app: app-nath-python
  on:
    branch: master
  api_key:
    secure: Ulpsy/liOoES0ZeuKHMovKmhHE7Oay6t+r7h82C26hD+m+Kbw+UkyFmL60l1/O0Q3h06Gfdu7J0L08zTnC7ItXh3bxDO1roCgU8ysoqThFmq7cSljuO69PmbzRsnrsQsO6szfIiEY6nfYho614gfsgobPNicIDttK3OiOM0V0pBslXrGLp0zyUj0+15ypJbi+pGpOyzWL+xU2mrgF8ufIHrYLvZCaXvJudanNY3NMmTN3UBhSJqVTcb0nQbjonqFu9Ie/1avgZNTp+NFDYljwVGB5ep4nVWjKrE5L8FQj3RqZlJN+GhMgCmSEEWQgttGcDcZcLO5atPAlwOHfRkKuNOre1r/CEUOdpur0RABLOdxuBrZA4TiJkeHbjam26+Ur3+MIrFSLRWYVtS9kpj4fr2WB4aB0MTV1NFGuFCPBfkW7BLUagfKljnNNWRqaRnuNsVQOi9wbHbmMm5VLWjJNv4qyVSnxwC/htWZdcp7/ctqrzvrA58pTJgdkWM1Km3OJTqi/o/HuiVtmqpYUBPOIhD4UxX3br7uMeSDrWMzNZ4XxZTW+eagUxaRhEGAH8+IKntQz5rAxq7Drd7DKOqWcKqCBwXcrhXYR0QFabftlyUKiBIFQqH7guy+M9e9r3YgmoLiwkmda+e1kQSxxWwHNk5T1EHgitIrIcRJBByWNmY=
