language: python
python:
- 3.6.3
script:
- python test.py
deploy:
  provider: heroku
  app: app-nath-python
  on:
    branch: master
  api_key:
    secure: oOc9Wt7TWJXtWi5PMBky0O6dg8IWAJjSxxcFHoYcAC6pe4UnvB39ifBdigighzCbEg7WU6S+kCKLCG9Nf4oNhizUoxADUNd5q5Mbc8xfDyt6uFpAVo+G23uAJWENPH4LKxYIljTNwTKjmO5TudvxvDzbdxxFz+1OO2yAJx9IOjvdqGTR1Be+VEICzk8buUdk8h5X1e5rpQ0TtnK2D6xdd3b36pzdy7QR867MBz7cDQgO8NZJf4s8q0xq/TmqLgo8YXCcMrQ1C/Xtdu/H49FxmDagW7rwJDv6LyMfg9OfoRLitW1Ir9pegCZE5FpWMEkyxGwyPf93KI0/gXbZujVGCa6PKdiCdRPx8cKFVwMe63On1dFVrDcoJ4/fjeBAbtZpI4K10s+aSQDf3k3NUuUDgfpsQY89odkGqk7KzUaDmc6/cCEexjRJ4GglEcvhhBCwZjiQsqdcg7L9Isop1E43y081lXDqXELaK1bbdrQ8TO35C7v94bspyySwm5RKv1nvExsgvamsjITXV5Rxopt5Mkjlgmrs6mAChxFx18Ibv7rsSpfV29+OQKgTIL7RDIHY1lEVHb9vbyu6a2Dsiw90MXhOojrhj5TQtrmqJ4PjuUDNbVHp7Mmv9u46WweRaV3jxh/QKFZIj9/AoGNPVCHT0uYJ35Xe23oQDs5wVJbgtW8=
