language: python
python:
- 3.6.3
script:
- python test.py
deploy:
  provider: heroku
  app: app-nath-python
  on:
    branch: master
  api_key:
    secure: XIBWZfPqmdeE7l2QsGLL3WKvBmSQLN0/Rm6hDXcSFyb+jStp3lL5r2Zdly3J/GAm+R3WHCbly+MBOdVq68KndgM4pjfTu4ZxewOoEt77cdK6NmdDjBT/H7L/4Kdf6bh66+bSE5bxv2p0uh1gW2koinMkRFDsl94bWK/ljsxLlhIJJ/xCoOZpJ/Ua5DH2kUfVU3TFAD8W/vz0IEzzRJvSGgOMgbks0YND3aDVQLJwlPhM6cx0mvqtO1XFntH9k9riJFo/g2/ktsjnyNHVb4eh6zxshUdQV+F0GiouH0G/dCKLJbzrOIqKau8A/AZEpWHxneT1pMAhjU/PLtthQkuiyfnu6jAt9BP3lb/2/iZ9prtQavsg7xJic85Aghvc5E3jppxHZIDULFL2ZM5RCDnvXi8HOubLn1LeWB50EttNTBYH8sHhbFQK5oYizXr7bwaGETl1yXMikbsAGAv4dALv/zDseOMA4Yn1mTJGBMnNH56ZBWKKJsfoLP1qcA2YLUveGu+h4Q1jPiZ37pesIj0V4gDLS+Y7PZ4bkr1eeApME7hKeJyjIlZTDI7lfSCoXd/vL4Q97gQWwSb76lLZCVJHEdlAXHcszYT57f4bII2nrtHBRtMe9EdG/fTgffpbHsj6BQrkp8xdVKAvAKBsxMqnhMM/geLi9+23i5cHQKDvLrw=
