language: python
python:
- 3.6.3
script:
- python test.py
deploy:
  provider: heroku
  app: app-portfolio-nath
  on:
    branch: master
  api_key:
    secure: FBuDRNuCZH752qDlfhPBKtAhgxj5Uhg3+Dhne55BKctRoQjj3MM9qzVauAPF1wGGGeU88gc0BbvNZBQEckL+somHGpbC1Ak8p4beK6MGcCry5tlTkKNc2wfL1770+YVpoyaQC7+F3KWmHGRFTSt0KGXH6Irv0mutO/K+9pl0+NH/AN+bt81X1ZlvNpumvej/6l6SKPzKif3rkSTjheEcxP8XtcberIXiJNYBkP/aX/W2gDWIlr8bk+OQfv4GFc/x6BOLL62wEthq6c3LJmERbcAC8ZtLkbbGvwa9bSwatzsZJuZ9ilWtvHSjlKlKxa47bsjVdAaena4At4SyzuKJU6UnGVqyt29ep0F3YklRxQAfkxNqw2iy/jaLVUpgRL7hlhdsIp2eN7zVtSEpC6XJW5dAwXWksIdysZWSBKYDgcTFP3gn0uKFNOcyNxEwSpXVNVmsw/HZFEXaSXENLcizvqeOSI/WsSmMynA62NOmCLOxRxQEFtu64VKpioSYiSqNXqvfA3LGFuqWOZuO1ER3PVaWdPRYsHQ9t0sxlc2pOgOCpU3ScqAXJYIAMMl/xj2U5T1P5H72rmp7q85WNC/nwykWrUBcqGMGxk7CoTQkcMzjpHLAdOS4GwFr2Isi6bi2C4IVEBGMVQ7dB4tXI13c4qYeVtqyQBInL0DZa2dYxS8=
